import type { Metadata } from "next";
import "./globals.css";
import { secondary } from "./fonts";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Khalsa College Lyallpur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={secondary.className}>
        <div className="absolute top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]">
          {children}
        </div>
      </body>
    </html>
  );
}
